# Generated by Django 5.0.3 on 2024-05-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_done',
            field=models.TextField(blank=True, null=True),
        ),
    ]
